import type { NextPage } from "next";
import Head from "next/head";
import ResultCarousel from "../components/ResultCarousel";
import { useQuery } from "react-query";
import SolidButton from "../components/SolidButton";
import axios from "axios";
import { useNetwork, useSwitchNetwork } from 'wagmi'

const Home: NextPage = () => {

  const network = useSwitchNetwork({
    chainId: 80001,
  })

  const fetchImages = async () => {
    const res = await axios.get('http://localhost:3001/diffemon');
    console.log(res)
    return res.data;
  }

  const { data: images, isLoading, refetch } = useQuery(['images'], fetchImages, {
    enabled: false
  });

  return (
    <>
      <Head>
        <title>UnstableLabs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/flask.png" />
      </Head>
      <main className="container mx-auto w-4/5 p-10">
        <div className="mt-4 relative ">
          <img src="/lab-top.png" alt="lab-top" className="w-full" />
          <div className="w-full absolute bg-black bottom-1/2 ">
            <p className="font-pixel font-bold text-3xl text-white text-center">Welcome to <span className="text-acid">Unstable</span>Labs!</p>
            <p className="font-pixel font-bold text-lg text-gray-400 text-center">a lab to brew AI-generated NFTs</p>
          </div>
        </div>
        <div className="flex mt-10 justify-center items-center ">
          <p className="font-pixel font-bold text-3xl text-white">Step into the Brewery</p>
        </div>
        <img src="/brewery-animated.gif" className="w-72 mx-auto mt-16" />
        <div className="bg-gray-400 p-6 w-2/3 mx-auto mt-16 row-start-3 col-start-3">
          <div className="flex space-x-5">
            <input type="text" className="w-full p-4 placeholder:font-pixel text-black outline-none font-pixel" placeholder="Enter your description" />
            <SolidButton text="Brew" onClick={() => refetch()} />
          </div>
        </div>
        {isLoading && <div className="flex justify-center mt-8">
          <img src="/flask-combining.gif" alt="loading" className="w-64" />
        </div>}
        {images && <div className="w-full mt-24">
          <ResultCarousel images={images} />
        </div>}
        <div className="mt-24 flex space-x-4">
          <img src="/barrel-toxic.gif" alt="barrel" className="w-24" />
          <img src="/barrels.png" alt="barrels" className="w-56" />
          <img src="/pc-animated.gif" alt="barrels" className="w-48" />

        </div>
      </main>
    </>
  );
};

export default Home;

